_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 10
precision: 16
gradient_clip_val: 1.
val_check_interval: 0.5

weights_summary: null
progress_bar_refresh_rate: 10
